from __future__ import annotations

from sqlalchemy import (
    Boolean,
    Column,
    Date,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    Index,
    JSON,
    MetaData,
    String,
    Table,
    Text,
    UniqueConstraint,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.sql import func

metadata = MetaData()
JSON_DOCUMENT = JSONB().with_variant(JSON(), "sqlite")

data_sources = Table(
    "data_sources",
    metadata,
    Column("source_id", String, primary_key=True),
    Column("name", String, nullable=False),
    Column("source_type", String, nullable=False),
    Column("config", JSON_DOCUMENT, nullable=False, default=dict),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
)

jobs = Table(
    "jobs",
    metadata,
    Column("job_id", String, primary_key=True),
    Column("job_type", String, nullable=False),
    Column("scope_key", String, nullable=False),
    Column("status", String, nullable=False),
    Column("payload", JSON_DOCUMENT, nullable=False, default=dict),
    Column("result", JSON_DOCUMENT, nullable=False, default=dict),
    Column("error", JSON_DOCUMENT, nullable=False, default=dict),
    Column("current_step", String, nullable=True),
    Column("priority", Integer, nullable=False, default=0),
    Column("locked_by", String, nullable=True),
    Column("lock_expires_at", DateTime(timezone=True), nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column("started_at", DateTime(timezone=True), nullable=True),
    Column("finished_at", DateTime(timezone=True), nullable=True),
    Column("heartbeat_at", DateTime(timezone=True), nullable=True),
)

Index("ix_jobs_status_priority_created", jobs.c.status, jobs.c.priority, jobs.c.created_at)
Index("ix_jobs_scope_key", jobs.c.scope_key)

worker_heartbeats = Table(
    "worker_heartbeats",
    metadata,
    Column("worker_id", String, primary_key=True),
    Column("status", String, nullable=False),
    Column("current_job_id", String, nullable=True),
    Column("current_step", String, nullable=True),
    Column("started_at", DateTime(timezone=True), nullable=False),
    Column("last_seen_at", DateTime(timezone=True), nullable=False),
)

Index("ix_worker_heartbeats_last_seen", worker_heartbeats.c.last_seen_at)

market_data_refs = Table(
    "market_data_refs",
    metadata,
    Column("dataset_id", String, primary_key=True),
    Column("source_id", ForeignKey("data_sources.source_id"), nullable=False),
    Column("asset", String, nullable=False),
    Column("instrument", String, nullable=False),
    Column("data_type", String, nullable=False),
    Column("timeframe", String, nullable=True),
    Column("data_origin", String, nullable=False, default="raw"),
    Column("start_ts", DateTime(timezone=True), nullable=True),
    Column("end_ts", DateTime(timezone=True), nullable=True),
    Column("row_count", Integer, nullable=True),
    Column("storage_backend", String, nullable=False),
    Column("storage_uri", Text, nullable=False),
    Column("schema_descriptor", JSON_DOCUMENT, nullable=False, default=dict),
    Column("quality_status", String, nullable=False, default="unknown"),
    Column("ingestion_version", String, nullable=False),
    UniqueConstraint("source_id", "instrument", "data_type", "timeframe", "data_origin", "ingestion_version"),
)

signal_engines = Table(
    "signal_engines",
    metadata,
    Column("signal_engine_id", String, primary_key=True),
    Column("name", String, nullable=False),
    Column("description", Text, nullable=False, default=""),
)

signal_engine_versions = Table(
    "signal_engine_versions",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("signal_engine_id", ForeignKey("signal_engines.signal_engine_id"), nullable=False),
    Column("version", String, nullable=False),
    Column("code_ref", JSON_DOCUMENT, nullable=False),
    Column("supported_input_data_types", JSON_DOCUMENT, nullable=False, default=list),
    Column("required_data", JSON_DOCUMENT, nullable=False, default=list),
    Column("output_envelope_version", String, nullable=False),
    Column("runtime_entrypoint", String, nullable=False),
    Column("live_scanner_entrypoint", String, nullable=True),
    Column("configuration_schema", JSON_DOCUMENT, nullable=False, default=dict),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    UniqueConstraint("signal_engine_id", "version"),
)

signal_sets = Table(
    "signal_sets",
    metadata,
    Column("signal_set_key", String, primary_key=True),
    Column("signal_set_id", String, nullable=False),
    Column("signal_engine_id", String, nullable=False),
    Column("signal_engine_version", String, nullable=False),
    Column("asset", String, nullable=False),
    Column("instrument", String, nullable=False),
    Column("start_ts", DateTime(timezone=True), nullable=True),
    Column("end_ts", DateTime(timezone=True), nullable=True),
    Column("packet_count", Integer, nullable=False, default=0),
    Column("payload_schema", String, nullable=False),
    Column("source_path", Text, nullable=False),
    Column("manifest", JSON_DOCUMENT, nullable=False, default=dict),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    UniqueConstraint("signal_engine_id", "asset", "signal_set_id"),
)

signals = Table(
    "signals",
    metadata,
    Column("signal_id", String, primary_key=True),
    Column("signal_set_key", ForeignKey("signal_sets.signal_set_key"), nullable=True),
    Column("signal_engine_id", String, nullable=False),
    Column("signal_engine_version", String, nullable=False),
    Column("asset", String, nullable=False),
    Column("instrument", String, nullable=False),
    Column("timestamp", DateTime(timezone=True), nullable=False),
    Column("data_refs", JSON_DOCUMENT, nullable=False, default=list),
    Column("payload_schema", String, nullable=False),
    Column("payload", JSON_DOCUMENT, nullable=False, default=dict),
)

strategy_modules = Table(
    "strategy_modules",
    metadata,
    Column("strategy_id", String, primary_key=True),
    Column("name", String, nullable=False),
    Column("description", Text, nullable=False, default=""),
)

strategy_versions = Table(
    "strategy_versions",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("strategy_id", ForeignKey("strategy_modules.strategy_id"), nullable=False),
    Column("version", String, nullable=False),
    Column("code_ref", JSON_DOCUMENT, nullable=False),
    Column("supported_signal_engine_ids", JSON_DOCUMENT, nullable=False, default=list),
    Column("parameter_schema", JSON_DOCUMENT, nullable=False, default=dict),
    Column("decision_schema", JSON_DOCUMENT, nullable=False, default=dict),
    Column("execution_profile_schema", JSON_DOCUMENT, nullable=False, default=dict),
    Column("test_suite_status", String, nullable=False, default="unknown"),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    UniqueConstraint("strategy_id", "version"),
)

walk_forward_templates = Table(
    "walk_forward_templates",
    metadata,
    Column("template_id", String, primary_key=True),
    Column("anchor", String, nullable=False),
    Column("retrain_cadence", String, nullable=False),
    Column("train_range", String, nullable=False),
    Column("walk_forward_range", String, nullable=False),
    Column("embargo", String, nullable=False),
    Column("scoring_profile", String, nullable=False),
    Column("promotion_gate", String, nullable=False),
)

walk_forward_runs = Table(
    "walk_forward_runs",
    metadata,
    Column("run_id", String, primary_key=True),
    Column("template_id", ForeignKey("walk_forward_templates.template_id"), nullable=False),
    Column("strategy_id", String, nullable=False),
    Column("signal_engine_id", String, nullable=False),
    Column("asset", String, nullable=False),
    Column("train_start", Date, nullable=False),
    Column("train_end", Date, nullable=False),
    Column("walk_forward_start", Date, nullable=False),
    Column("walk_forward_end", Date, nullable=False),
    Column("status", String, nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
)

stage0_universe_runs = Table(
    "stage0_universe_runs",
    metadata,
    Column("universe_run_id", String, primary_key=True),
    Column("name", String, nullable=True),
    Column("config_hash", String, nullable=False),
    Column("window_start", DateTime(timezone=True), nullable=False),
    Column("window_end", DateTime(timezone=True), nullable=False),
    Column("train_start", Date, nullable=True),
    Column("train_end", Date, nullable=True),
    Column("walk_forward_start", Date, nullable=True),
    Column("walk_forward_end", Date, nullable=True),
    Column("forward_hours", Integer, nullable=False),
    Column("trigger_rate_threshold_pct", Float, nullable=False),
    Column("engine_filter", JSON_DOCUMENT, nullable=False, default=list),
    Column("status", String, nullable=False),
    Column("summary", JSON_DOCUMENT, nullable=False, default=dict),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
)

stage0_universe_candidates = Table(
    "stage0_universe_candidates",
    metadata,
    Column("candidate_id", String, primary_key=True),
    Column("universe_run_id", ForeignKey("stage0_universe_runs.universe_run_id"), nullable=False),
    Column("signal_set_key", ForeignKey("signal_sets.signal_set_key"), nullable=False),
    Column("signal_engine_id", String, nullable=False),
    Column("signal_engine_version", String, nullable=False),
    Column("asset", String, nullable=False),
    Column("signal_set_id", String, nullable=False),
    Column("packet_count", Integer, nullable=False),
    Column("trigger_rate_pct", Float, nullable=True),
    Column("branch_path", String, nullable=False),
    Column("acceptance_status", String, nullable=False),
    Column("duplicate_status", String, nullable=False),
    Column("existing_strategy_id", String, nullable=True),
    Column("last_error", JSON_DOCUMENT, nullable=False, default=dict),
    Column("metrics", JSON_DOCUMENT, nullable=False, default=dict),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    UniqueConstraint("universe_run_id", "signal_set_key"),
)

stage1_research_sessions = Table(
    "stage1_research_sessions",
    metadata,
    Column("session_id", String, primary_key=True),
    Column("source_universe_run_id", ForeignKey("stage0_universe_runs.universe_run_id"), nullable=False),
    Column("source_candidate_id", ForeignKey("stage0_universe_candidates.candidate_id"), nullable=False),
    Column("signal_set_key", ForeignKey("signal_sets.signal_set_key"), nullable=False),
    Column("signal_engine_id", String, nullable=False),
    Column("signal_engine_version", String, nullable=False),
    Column("asset", String, nullable=False),
    Column("signal_set_id", String, nullable=False),
    Column("strategy_id", String, nullable=False),
    Column("strategy_version", String, nullable=False),
    Column("train_start", Date, nullable=False),
    Column("train_end", Date, nullable=False),
    Column("walk_forward_start", Date, nullable=False),
    Column("walk_forward_end", Date, nullable=False),
    Column("artifact_root", Text, nullable=False),
    Column("status", String, nullable=False),
    Column("seed_strategy_source_type", String, nullable=True),
    Column("seed_strategy_source_path", Text, nullable=True),
    Column("seed_strategy_source_version", String, nullable=True),
    Column("seed_strategy_source_session_id", String, nullable=True),
    Column("manifest", JSON_DOCUMENT, nullable=False, default=dict),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    UniqueConstraint("source_candidate_id", "strategy_id", "strategy_version"),
)

strategy_development_runs = Table(
    "strategy_development_runs",
    metadata,
    Column("run_id", String, primary_key=True),
    Column("stage", String, nullable=False),
    Column("strategy_id", String, nullable=False),
    Column("strategy_version", String, nullable=False),
    Column("signal_engine_id", String, nullable=False),
    Column("signal_engine_version", String, nullable=False),
    Column("signal_set_key", ForeignKey("signal_sets.signal_set_key"), nullable=False),
    Column("asset", String, nullable=False),
    Column("forward_hours", Integer, nullable=False),
    Column("significance_threshold_pct", Float, nullable=True),
    Column("artifact_root", Text, nullable=False),
    Column("commands", JSON_DOCUMENT, nullable=False, default=dict),
    Column("status", String, nullable=False),
    Column("metrics", JSON_DOCUMENT, nullable=False, default=dict),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
)

backtest_runs = Table(
    "backtest_runs",
    metadata,
    Column("run_id", String, primary_key=True),
    Column("template_id", String, nullable=False),
    Column("stage", String, nullable=False),
    Column("strategy_id", String, nullable=False),
    Column("strategy_version", String, nullable=False),
    Column("signal_engine_id", String, nullable=False),
    Column("signal_engine_version", String, nullable=False),
    Column("asset", String, nullable=False),
    Column("instrument", String, nullable=False),
    Column("dataset_refs", JSON_DOCUMENT, nullable=False, default=list),
    Column("parameters_hash", String, nullable=False),
    Column("status", String, nullable=False),
    Column("metrics", JSON_DOCUMENT, nullable=False, default=dict),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
)

stage_runs = Table(
    "stage_runs",
    metadata,
    Column("stage_run_id", String, primary_key=True),
    Column("walk_forward_run_id", ForeignKey("walk_forward_runs.run_id"), nullable=True),
    Column("stage", String, nullable=False),
    Column("strategy_id", String, nullable=False),
    Column("strategy_version", String, nullable=False),
    Column("signal_engine_id", String, nullable=False),
    Column("signal_engine_version", String, nullable=False),
    Column("dataset_refs", JSON_DOCUMENT, nullable=False, default=list),
    Column("status", String, nullable=False),
    Column("metrics", JSON_DOCUMENT, nullable=False, default=dict),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
)

decisions = Table(
    "decisions",
    metadata,
    Column("decision_id", String, primary_key=True),
    Column("stage_run_id", ForeignKey("stage_runs.stage_run_id"), nullable=False),
    Column("signal_id", ForeignKey("signals.signal_id"), nullable=False),
    Column("strategy_id", String, nullable=False),
    Column("strategy_version", String, nullable=False),
    Column("action", String, nullable=False),
    Column("direction", String, nullable=False),
    Column("confidence", Float, nullable=False),
    Column("reason_code", String, nullable=False),
    Column("execution_profile", JSON_DOCUMENT, nullable=False, default=dict),
    Column("diagnostics", JSON_DOCUMENT, nullable=False, default=dict),
)

score_summaries = Table(
    "score_summaries",
    metadata,
    Column("score_id", String, primary_key=True),
    Column("stage_run_id", ForeignKey("stage_runs.stage_run_id"), nullable=False),
    Column("scoring_method", String, nullable=False),
    Column("metrics", JSON_DOCUMENT, nullable=False, default=dict),
    Column("records_uri", Text, nullable=True),
    Column("summary", Text, nullable=False),
)

agent_tasks = Table(
    "agent_tasks",
    metadata,
    Column("task_id", String, primary_key=True),
    Column("walk_forward_run_id", ForeignKey("walk_forward_runs.run_id"), nullable=False),
    Column("stage", String, nullable=False),
    Column("strategy_id", String, nullable=False),
    Column("strategy_version", String, nullable=False),
    Column("task_bundle_uri", Text, nullable=False),
    Column("input_bundle_hash", String, nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
)

agent_runs = Table(
    "agent_runs",
    metadata,
    Column("agent_run_id", String, primary_key=True),
    Column("task_id", ForeignKey("agent_tasks.task_id"), nullable=False),
    Column("provider", String, nullable=False),
    Column("prompt_hash", String, nullable=False),
    Column("output_diff_uri", Text, nullable=True),
    Column("audit_note_uri", Text, nullable=True),
    Column("status", String, nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
)

execution_bundles = Table(
    "execution_bundles",
    metadata,
    Column("bundle_id", String, primary_key=True),
    Column("asset", String, nullable=False),
    Column("instrument", String, nullable=False),
    Column("signal_engine_id", String, nullable=False),
    Column("signal_engine_version", String, nullable=False),
    Column("strategy_id", String, nullable=False),
    Column("strategy_version", String, nullable=False),
    Column("source_stage1_session_id", ForeignKey("stage1_research_sessions.session_id"), nullable=False),
    Column("source_stage4_result_path", Text, nullable=False),
    Column("bundle_uri", Text, nullable=False),
    Column("strategy_module_ref", Text, nullable=False),
    Column("execution_setup", JSON_DOCUMENT, nullable=False, default=dict),
    Column("risk_limits", JSON_DOCUMENT, nullable=False, default=dict),
    Column("evidence_refs", JSON_DOCUMENT, nullable=False, default=dict),
    Column("content_hash", String, nullable=False),
    Column("status", String, nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    UniqueConstraint("content_hash"),
)

deployment_routes = Table(
    "deployment_routes",
    metadata,
    Column("route_id", String, primary_key=True),
    Column("active_bundle_id", ForeignKey("execution_bundles.bundle_id"), nullable=True),
    Column("strategy_id", String, nullable=False),
    Column("strategy_version", String, nullable=False),
    Column("signal_engine_id", String, nullable=False),
    Column("signal_engine_version", String, nullable=False),
    Column("asset", String, nullable=False),
    Column("instrument", String, nullable=False),
    Column("account_mode", String, nullable=False),
    Column("execution_adapter", String, nullable=False),
    Column("exchange_account", String, nullable=False, default="default"),
    Column("cron_interval_minutes", Integer, nullable=False, default=5),
    Column("margin_allocation_pct", Float, nullable=False, default=10.0),
    Column("leverage", Float, nullable=False, default=1.0),
    Column("manual_sizing_enabled", Boolean, nullable=False, default=False),
    Column("scheduler_status", String, nullable=False, default="stopped"),
    Column("auto_submit_enabled", Boolean, nullable=False, default=True),
    Column("last_wake_at", DateTime(timezone=True), nullable=True),
    Column("last_wake_id", String, nullable=True),
    Column("next_wake_at", DateTime(timezone=True), nullable=True),
    Column("last_lifecycle_error", JSON_DOCUMENT, nullable=False, default=dict),
    Column("risk_limits", JSON_DOCUMENT, nullable=False),
    Column("promoted", Boolean, nullable=False, default=False),
    Column("data_warmed", Boolean, nullable=False, default=False),
    Column("manually_armed", Boolean, nullable=False, default=False),
    Column("enabled", Boolean, nullable=False, default=False),
    Column("archived", Boolean, nullable=False, default=False),
    Column("archived_at", DateTime(timezone=True), nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    UniqueConstraint("asset", "account_mode", "execution_adapter", "exchange_account"),
)

wake_runs = Table(
    "wake_runs",
    metadata,
    Column("wake_id", String, primary_key=True),
    Column("route_id", ForeignKey("deployment_routes.route_id"), nullable=False),
    Column("bundle_id", ForeignKey("execution_bundles.bundle_id"), nullable=True),
    Column("status", String, nullable=False),
    Column("branch", String, nullable=False),
    Column("blockers", JSON_DOCUMENT, nullable=False, default=list),
    Column("exchange_snapshot", JSON_DOCUMENT, nullable=False, default=dict),
    Column("signal_scan_result", JSON_DOCUMENT, nullable=False, default=dict),
    Column("strategy_decision", JSON_DOCUMENT, nullable=False, default=dict),
    Column("order_intents", JSON_DOCUMENT, nullable=False, default=list),
    Column("adapter_results", JSON_DOCUMENT, nullable=False, default=list),
    Column("error", JSON_DOCUMENT, nullable=False, default=dict),
    Column("started_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column("completed_at", DateTime(timezone=True), nullable=True),
)

owner_states = Table(
    "owner_states",
    metadata,
    Column("owner_state_id", String, primary_key=True),
    Column("route_id", ForeignKey("deployment_routes.route_id"), nullable=False),
    Column("bundle_id", ForeignKey("execution_bundles.bundle_id"), nullable=False),
    Column("position_instance_id", String, nullable=True),
    Column("asset", String, nullable=False),
    Column("instrument", String, nullable=False),
    Column("account_mode", String, nullable=False),
    Column("owner_strategy_id", String, nullable=False),
    Column("owner_strategy_version", String, nullable=False),
    Column("opened_from_signal_id", String, nullable=True),
    Column("position_state", JSON_DOCUMENT, nullable=False, default=dict),
    Column("status", String, nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column("closed_at", DateTime(timezone=True), nullable=True),
)

audit_log = Table(
    "audit_log",
    metadata,
    Column("audit_id", String, primary_key=True),
    Column("entity_type", String, nullable=False),
    Column("entity_id", String, nullable=False),
    Column("event_type", String, nullable=False),
    Column("payload", JSON_DOCUMENT, nullable=False, default=dict),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
)
